import 'package:sheryan/app/core/models/hospital_mode.dart';
import 'package:sheryan/app/core/models/hospital_type_model.dart';
import 'package:sheryan/app/core/models/latlng_model.dart';
import 'package:sheryan/app/core/models/pathological_case_model.dart';

List<PathologicalCase> pathologicalCases = [
  PathologicalCase(id: 1, level: 6, name: "حادث مروري"),
  PathologicalCase(id: 2, level: 5, name: "ضيق تنفس"),
  PathologicalCase(id: 3, level: 1, name: "ولادة"),
  PathologicalCase(id: 4, level: 4, name: "فقدان الوعي"),
  PathologicalCase(id: 5, level: 9, name: "توقف القلب"),
  PathologicalCase(id: 6, level: 8, name: "حريق "),
  PathologicalCase(id: 7, level: 3, name: " كسر "),
  PathologicalCase(id: 8, level: 7, name: " سقوط من مبنى"),
  PathologicalCase(id: 9, level: 2, name: " غير ذلك"),
];
List<HospitalType> hospitalTypes = [
  HospitalType(name: "حكومي", id: 1),
  HospitalType(name: "خاص", id: 2)
];
List<Hospital> hospitales = [
  Hospital(
    id: 1,
    name: "الرازي",
    address: "حلب_الرازي",
    hospitalType: HospitalType(name: "حكومي", id: 1),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "الجامعة",
    address: "حلب _الجامعة",
    hospitalType: HospitalType(name: "حكومي", id: 1),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "ابن رشد",
    address: "حلب_السريان الجديدة",
    hospitalType: HospitalType(name: "حكومي", id: 1),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "الأمل الجراحي",
    address: "حلب_منبج",
    hospitalType: HospitalType(name: "حكومي", id: 1),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "التوليد الجامعي",
    address: "حلب_الجامعة",
    hospitalType: HospitalType(name: "حكومي", id: 1),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "العيون التخصصي",
    address: "حلب_قاضي عسكر",
    hospitalType: HospitalType(name: "حكومي", id: 1),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "الكندي الجامعي",
    address: "حلب_المسلمية",
    hospitalType: HospitalType(name: "حكومي", id: 1),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "المشفى العسكري",
    address: "حلب_الجميلية",
    hospitalType: HospitalType(name: "حكومي", id: 1),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "الهلال الأحمر",
    address: "حلب_السليمانية",
    hospitalType: HospitalType(name: "حكومي", id: 1),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "تل عرن الجراحي",
    address: "حلب_تل عرن",
    hospitalType: HospitalType(name: "حكومي", id: 1),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "زاهي أزرق",
    address: "حلب_بستان باشا",
    hospitalType: HospitalType(name: "حكومي", id: 1),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "مركز الباسل للأمراض وجراحة القلب",
    address: "حلب_الأشرفية",
    hospitalType: HospitalType(name: "حكومي", id: 1),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "مشفى التوليد الحكومي",
    address: "حلب_المحافظة",
    hospitalType: HospitalType(name: "حكومي", id: 1),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "عبد الجبار الشيحان",
    address: "حلب_شارع تشرين",
    hospitalType: HospitalType(name: "حكومي", id: 1),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  //////////////////////////////////////////////////////////////////////////////////////////////
  ///
  Hospital(
    id: 1,
    name: "الاستشاري الحديث",
    address: "حلب_المارتيني",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "الاسعاف الجراحي",
    address: "حلب_الشعار",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " الأشتر",
    address: "حلب_المحافظة",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " الأطفال التخصصي",
    address: "حلب_سيف الدولة",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " الأمل",
    address: "حلب_شارع تشرين",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "الأمير ",
    address: "حلب_المحافظة",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "الأميري ",
    address: "حلب_التلل",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "الأندلس الطبي ",
    address: "حلب_شارع النيل",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "البيان ",
    address: "حلب_الشعار",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " الجابري",
    address: "حلب_الجابرية",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " الحكمة",
    address: "حلب_حي السبيل",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " الحكيم",
    address: "حلب_الشعار",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " الحياة الجراحي",
    address: "حلب_الحريري",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "الدقاق الجراحي ",
    address: "حلب_الشعار",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " الرجاء",
    address: "حلب_حلب الجديدة",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " الرجمة",
    address: "حلب_الأشرفية",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "الرسالة ",
    address: "حلب_االرازي",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " الرياض",
    address: "حلب_جمعية الزهراء",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " الزيتوني",
    address: "حلب_حلب الجديدة",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "السبيل الجراحي ",
    address: "حلب_حي السبيل",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " السراج",
    address: "حلب_حي السبيل",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "السكري ",
    address: "حلب_السكري",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "السلام ",
    address: "حلب_السريان الجديدة",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "السلام للأطفال ",
    address: "حلب_باب الحديد",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "السيدة الزهراء ",
    address: "حلب_الشعار",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " الشامي",
    address: "حلب_الجميلية",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " الشهباء التخصصي",
    address: "حلب_حلب الجديدة",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " العاصي",
    address: "حلب_الشهباء",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " العطار",
    address: "حلب_شارع فيصل",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " الفارابي",
    address: "حلب_حريتان",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "الفرح ",
    address: "حلب_بستان باشا",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "الفرقان ",
    address: "حلب_الفرقان",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " القديس لويس",
    address: "حلب_الاسماعيلية",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "الكلمة ",
    address: "حلب_حي السبيل",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " المارتيني",
    address: "حلب_المارتيني",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " المحبة",
    address: "حلب_شيخ مقصود",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " المركزي",
    address: "حلب_الحريري",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "المستقبل ",
    address: "حلب_الحمدانية",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "المشفى العربي ",
    address: "حلب_شارع النيل",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " الميدان للتوليد",
    address: "حلب_الميدان",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " النائف",
    address: "حلب_سيف الدولة",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " النحاس",
    address: "حلب_سيف الدولة",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " النور",
    address: "حلب_الزبدية",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " الهلال الأحمر",
    address: "حلب_السليمانية",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "الوفاء ",
    address: "حلب_الحريري",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " بدرخان الجراحي",
    address: "حلب_الجميلية",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " بشير الأجاتي",
    address: "حلب_شارع النيل",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " جبة جيان",
    address: "حلب_شارع فيصل",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "حلب للرعاية الصحية ",
    address: "حلب_الليرمون",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " حمدي الزعيم التخصصي",
    address: "حلب_الشهباء",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " حنان الجراحي",
    address: "حلب_الأشرفية",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "دار التوليد ",
    address: "حلب_المحافظة",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "دار الشفاء",
    address: "حلب_الشعار",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " دار شفاء مارجرجس",
    address: "حلب_السريان الجديدة",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " سامح جبل",
    address: "حلب_المحافظة",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " سلوم",
    address: "حلب_السليمانية",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " عابدين سليمان التخصصي",
    address: "حلب_الاشرفية",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " عيسى",
    address: "حلب_الحريري",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "فاعور ",
    address: "حلب_السليمانية",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " قلعة جي",
    address: "حلب_شارع النيل",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " الاحسان الجراحي",
    address: "حلب_الصاخور",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "السبيل ",
    address: "حلب_حي السبيل",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "الضبيط ",
    address: "حلب_المحافظة",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "الطونيان ",
    address: "حلب_العزيزية",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " المواساة",
    address: "حلب_باب الفرج",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "النحاس ",
    address: "حلب_شارع البارون",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " حلب الأهلي",
    address: "حلب_الفرقان",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " خير الله",
    address: "حلب_شارع القوتلي",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " زرزور",
    address: "حلب_الانصاري",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " محوك",
    address: "حلب_العزيزية",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "هشام السباعي ",
    address: "حلب_ الرازي",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " مظلوميان",
    address: "حلب_العزيزية",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " منيرجي",
    address: "حلب_المنشية القديمة",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " مهملات الجراحي",
    address: "حلب_الجميلية",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " ميسلون",
    address: "حلب_ميسلون",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: " نافع أسود",
    address: "حلب_السريان الجديدة",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
  Hospital(
    id: 1,
    name: "ياسين جبان ",
    address: "حلب_قاضي عسكر",
    hospitalType: HospitalType(name: "خاص", id: 2),
    carCount: 10,
    location: Latlng(31.2, 31.4),
  ),
];
